apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-project-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: cc-project
        image: yashkaka/yashdockerapp:latest
        ports:
        - containerPort: 3000


